# Generated by Django 5.2.2 on 2025-06-06 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
