# Generated by Django 5.2.2 on 2025-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_opportunity_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
